### ISSUE TITLE
Project does not have any documentation

### ISSUE THREAD

**Issue by wildcardjoker** [wildcardjoker/Numbers#17]
The project doesn't have any documentation. Admittedly, it's a pretty simple application, but if someone wants to write some documentation for it, I'll accept PRs that show some effort 🥇

**Comment by droffilc1** [comment]
I would like to contribute to this issue..

**Comment by wildcardjoker** [comment]
@droffilc1 Great, submit a PR 👍

**Comment by droffilc1** [comment]
@wildcardjoker Cool
