### ISSUE TITLE
Set focus after guess

### ISSUE THREAD

**Issue by wildcardjoker** [wildcardjoker/Numbers#29]
In the Winforms application, the focus should return to the guess textbox after the user has made a guess.
Currently, the user needs to click the Guess button and then click in the Guess input textbox to make another guess.

**Comment by rsk2** [comment]
Hi @wildcardjoker , can I work on this?

**Comment by wildcardjoker** [comment]
Feel free 😃

**Comment by rsk2** [comment]
@wildcardjoker , I have created a PR for this issue.

**Comment by wildcardjoker** [comment]
Nice work, @rsk2 . Before I approve the PR, why not select the text in `txtGuess` so the player can simply type the new number without having to backspace over the previous guess?

**Comment by wildcardjoker** [comment]
Resolved with PR #31
